version: '3.8'
services:
  spring-boot-postgres:
    image: spring-boot-postgres-image
    container_name: spring-boot-postgres-container
    networks:
      - spring-boot-postgres-network
    build:
      context: .
      dockerfile: Dockerfile-Gradle
    working_dir: /app
    env_file: .env
    depends_on:
      - db
    ports:
      - ${APPLICATION_PORT_ON_DOCKER_HOST}:${APPLICATION_PORT_ON_CONTAINER}
      - ${DEBUG_PORT_ON_DOCKER_HOST}:${DEBUG_PORT_ON_CONTAINER}
    volumes:
      - ./:/app
    command: ./gradlew bootRun

  db:
    container_name: login-app-db
    image: postgres:14.1-alpine
    env_file: .env
    ports:
      - ${DB_PORT_ON_DOCKER_HOST}:${DB_PORT_ON_CONTAINER}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - spring-boot-postgres-network

volumes:
  db:

networks:
  spring-boot-postgres-network: